version: '3'

services:
    myredis:
       image: redis
       expose:
           - '6379'
    
    webtrafficapp:
       build:
           dockerfile: Dockerfile
           context: ./
       ports:
           - '9999:9999'

       depends_on:
           - myredis